# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build anonymize-pdf-annotations - GUI for windows

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

    # Don't trigger if it's just a documentation update
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '**.yml'
      - '**.sh'
      - '**.bat'
      - 'tests/**'
      - 'doc/**'
      - '.vscode/*'
      - 'Dockerfile'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - '.dockerignore'
      - 'spec.json'
      - 'files.txt'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt
      - name: build binary
        run: |
          python setup.py build_binary
      - name: Print files 1
        run: |
          echo %cd%
          dir dist
      - name: Zip the folder
        run: |
          Compress-Archive dist/remove_name_from_annotations_gui.exe dist/remove_name_from_annotations_gui_win.zip

      - name: upload build
        uses: actions/upload-artifact@v3
        with:
          name: windows_executable
          path: './dist/remove_name_from_annotations_gui_win.zip'
      - name: Print files 2
        run: |
          echo %cd%
          dir dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            dist/remove_name_from_annotations_gui_win.zip